# Generated by Django 4.1 on 2022-08-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_changes_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='featuredmatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportsname', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
    ]
