# Generated by Django 4.1 on 2022-08-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_featuredmatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredmatches',
            name='eventname',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='featuredmatches',
            name='eventtime',
            field=models.TextField(default=None),
        ),
    ]
